if (typeof (window.BT) == 'undefined') { var BT = {}; }
BT.Util = BT.Util ? BT.Util : {};
if (!BT.Globals) { BT.Globals = {}; }

BT.Util.activate = function (p_$html) {

	p_$html.find('.bt-tooltip').tooltip({ trigger: 'hover' });
	p_$html.find('[data-toggle="popover"]').popover();
	p_$html.find('#fat-btn').button();
	//p_$html.find('.nav_app').dropdown();
	//p_$html.find('.dropdown').dropdown();
	console.log('BT.Util.activate');

}

BT.Util.GetLocalDateTimeFormat = function () {
	var formats = {
		"ar-sa": "dd/MM/yy",
		"bg-bg": "dd.M.yy",
		"ca-es": "dd/MM/yy",
		"zh-tw": "yy/M/d",
		"cs-cz": "d.M.yy",
		"da-dk": "dd-MM-yy",
		"de-de": "dd.MM.yy",
		"el-gr": "d/M/yy",
		"en-us": "M/d/yy",
		"fi-fi": "d.M.yy",
		"fr-fr": "dd/MM/yy",
		"he-il": "dd/MM/yy",
		"hu-hu": "yy. MM. dd.",
		"is-is": "d.M.yy",
		"it-it": "dd/MM/yy",
		"ja-jp": "yy/MM/dd",
		"ko-kr": "yy-MM-dd",
		"nl-nl": "d-M-yy",
		"nb-no": "dd.MM.yy",
		"pl-pl": "yy-MM-dd",
		"pt-br": "d/M/yy",
		"ro-ro": "dd.MM.yy",
		"ru-ru": "dd.MM.yy",
		"hr-hr": "d.M.yy",
		"sk-sk": "d. M. yy",
		"sq-al": "yy-MM-dd",
		"sv-se": "yy-MM-dd",
		"th-th": "d/M/yy",
		"tr-tr": "dd.MM.yy",
		"ur-pk": "dd/MM/yy",
		"id-id": "dd/MM/yy",
		"uk-ua": "dd.MM.yy",
		"be-by": "dd.MM.yy",
		"sl-si": "d.M.yy",
		"et-ee": "d.MM.yy",
		"lv-lv": "yy.MM.dd.",
		"lt-lt": "yy.MM.dd",
		"fa-ir": "MM/dd/yy",
		"vi-vn": "dd/MM/yy",
		"hy-am": "dd.MM.yy",
		"az-latn-az": "dd.MM.yy",
		"eu-es": "yy/MM/dd",
		"mk-mk": "dd.MM.yy",
		"af-za": "yy/MM/dd",
		"ka-ge": "dd.MM.yy",
		"fo-fo": "dd-MM-yy",
		"hi-in": "dd-MM-yy",
		"ms-my": "dd/MM/yy",
		"kk-kz": "dd.MM.yy",
		"ky-kg": "dd.MM.yy",
		"sw-ke": "M/d/yy",
		"uz-latn-uz": "dd/MM yy",
		"tt-ru": "dd.MM.yy",
		"pa-in": "dd-MM-yy",
		"gu-in": "dd-MM-yy",
		"ta-in": "dd-MM-yy",
		"te-in": "dd-MM-yy",
		"kn-in": "dd-MM-yy",
		"mr-in": "dd-MM-yy",
		"sa-in": "dd-MM-yy",
		"mn-mn": "yy.MM.dd",
		"gl-es": "dd/MM/yy",
		"kok-in": "dd-MM-yy",
		"syr-sy": "dd/MM/yy",
		"dv-mv": "dd/MM/yy",
		"ar-iq": "dd/MM/yy",
		"zh-cn": "yy/M/d",
		"de-ch": "dd.MM.yy",
		"en-gb": "dd/MM/yy",
		"es-mx": "dd/MM/yy",
		"fr-be": "d/MM/yy",
		"it-ch": "dd.MM.yy",
		"nl-be": "d/MM/yy",
		"nn-no": "dd.MM.yy",
		"pt-pt": "dd-MM-yy",
		"sr-latn-cs": "d.M.yy",
		"sv-fi": "d.M.yy",
		"az-cyrl-az": "dd.MM.yy",
		"ms-bn": "dd/MM/yy",
		"uz-cyrl-uz": "dd.MM.yy",
		"ar-eg": "dd/MM/yy",
		"zh-hk": "d/M/yy",
		"de-at": "dd.MM.yy",
		"en-au": "d/MM/yy",
		"es-es": "dd/MM/yy",
		"fr-ca": "yy-MM-dd",
		"sr-cyrl-cs": "d.M.yy",
		"ar-ly": "dd/MM/yy",
		"zh-sg": "d/M/yy",
		"de-lu": "dd.MM.yy",
		"en-ca": "dd/MM/yy",
		"es-gt": "dd/MM/yy",
		"fr-ch": "dd.MM.yy",
		"ar-dz": "dd-MM-yy",
		"zh-mo": "d/M/yy",
		"de-li": "dd.MM.yy",
		"en-nz": "d/MM/yy",
		"es-cr": "dd/MM/yy",
		"fr-lu": "dd/MM/yy",
		"ar-ma": "dd-MM-yy",
		"en-ie": "dd/MM/yy",
		"es-pa": "MM/dd/yy",
		"fr-mc": "dd/MM/yy",
		"ar-tn": "dd-MM-yy",
		"en-za": "yy/MM/dd",
		"es-do": "dd/MM/yy",
		"ar-om": "dd/MM/yy",
		"en-jm": "dd/MM/yy",
		"es-ve": "dd/MM/yy",
		"ar-ye": "dd/MM/yy",
		"en-029": "MM/dd/yy",
		"es-co": "dd/MM/yy",
		"ar-sy": "dd/MM/yy",
		"en-bz": "dd/MM/yy",
		"es-pe": "dd/MM/yy",
		"ar-jo": "dd/MM/yy",
		"en-tt": "dd/MM/yy",
		"es-ar": "dd/MM/yy",
		"ar-lb": "dd/MM/yy",
		"en-zw": "M/d/yy",
		"es-ec": "dd/MM/yy",
		"ar-kw": "dd/MM/yy",
		"en-ph": "M/d/yy",
		"es-cl": "dd-MM-yy",
		"ar-ae": "dd/MM/yy",
		"es-uy": "dd/MM/yy",
		"ar-bh": "dd/MM/yy",
		"es-py": "dd/MM/yy",
		"ar-qa": "dd/MM/yy",
		"es-bo": "dd/MM/yy",
		"es-sv": "dd/MM/yy",
		"es-hn": "dd/MM/yy",
		"es-ni": "dd/MM/yy",
		"es-pr": "dd/MM/yy",
		"am-et": "d/M/yy",
		"tzm-latn-dz": "dd-MM-yy",
		"iu-latn-ca": "d/MM/yy",
		"sma-no": "dd.MM.yy",
		"mn-mong-cn": "yy/M/d",
		"gd-gb": "dd/MM/yy",
		"en-my": "d/M/yy",
		"prs-af": "dd/MM/yy",
		"bn-bd": "dd-MM-yy",
		"wo-sn": "dd/MM/yy",
		"rw-rw": "M/d/yy",
		"qut-gt": "dd/MM/yy",
		"sah-ru": "MM.dd.yy",
		"gsw-fr": "dd/MM/yy",
		"co-fr": "dd/MM/yy",
		"oc-fr": "dd/MM/yy",
		"mi-nz": "dd/MM/yy",
		"ga-ie": "dd/MM/yy",
		"se-se": "yy-MM-dd",
		"br-fr": "dd/MM/yy",
		"smn-fi": "d.M.yy",
		"moh-ca": "M/d/yy",
		"arn-cl": "dd-MM-yy",
		"ii-cn": "yy/M/d",
		"dsb-de": "d. M. yy",
		"ig-ng": "d/M/yy",
		"kl-gl": "dd-MM-yy",
		"lb-lu": "dd/MM/yy",
		"ba-ru": "dd.MM.yy",
		"nso-za": "yy/MM/dd",
		"quz-bo": "dd/MM/yy",
		"yo-ng": "d/M/yy",
		"ha-latn-ng": "d/M/yy",
		"fil-ph": "M/d/yy",
		"ps-af": "dd/MM/yy",
		"fy-nl": "d-M-yy",
		"ne-np": "M/d/yy",
		"se-no": "dd.MM.yy",
		"iu-cans-ca": "d/M/yy",
		"sr-latn-rs": "d.M.yy",
		"si-lk": "yy-MM-dd",
		"sr-cyrl-rs": "d.M.yy",
		"lo-la": "dd/MM/yy",
		"km-kh": "yy-MM-dd",
		"cy-gb": "dd/MM/yy",
		"bo-cn": "yy/M/d",
		"sms-fi": "d.M.yy",
		"as-in": "dd-MM-yy",
		"ml-in": "dd-MM-yy",
		"en-in": "dd-MM-yy",
		"or-in": "dd-MM-yy",
		"bn-in": "dd-MM-yy",
		"tk-tm": "dd.MM.yy",
		"bs-latn-ba": "d.M.yy",
		"mt-mt": "dd/MM/yy",
		"sr-cyrl-me": "d.M.yy",
		"se-fi": "d.M.yy",
		"zu-za": "yy/MM/dd",
		"xh-za": "yy/MM/dd",
		"tn-za": "yy/MM/dd",
		"hsb-de": "d. M. yy",
		"bs-cyrl-ba": "d.M.yy",
		"tg-cyrl-tj": "dd.MM.yy",
		"sr-latn-ba": "d.M.yy",
		"smj-no": "dd.MM.yy",
		"rm-ch": "dd/MM/yy",
		"smj-se": "yy-MM-dd",
		"quz-ec": "dd/MM/yy",
		"quz-pe": "dd/MM/yy",
		"hr-ba": "d.M.yy.",
		"sr-latn-me": "d.M.yy",
		"sma-se": "yy-MM-dd",
		"en-sg": "d/M/yy",
		"ug-cn": "yy-M-d",
		"sr-cyrl-ba": "d.M.yy",
		"es-us": "M/d/yy"
	};

	var lng = window.navigator.userLanguage || window.navigator.language;

	return formats[lng.toLowerCase()] || "MM/dd/yy";
}
